/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsNewRouteImport } from './routes/workflows.new'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows.$workflowId'
import { Route as InstancesInstanceIdRouteImport } from './routes/instances.$instanceId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewRoute = WorkflowsNewRouteImport.update({
  id: '/workflows/new',
  path: '/workflows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesInstanceIdRoute = InstancesInstanceIdRouteImport.update({
  id: '/$instanceId',
  path: '/$instanceId',
  getParentRoute: () => InstancesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/instances': typeof InstancesRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/instances/$instanceId': typeof InstancesInstanceIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/instances': typeof InstancesRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/instances/$instanceId': typeof InstancesInstanceIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/instances': typeof InstancesRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/instances/$instanceId': typeof InstancesInstanceIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/instances'
    | '/templates'
    | '/instances/$instanceId'
    | '/workflows/$workflowId'
    | '/workflows/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/instances'
    | '/templates'
    | '/instances/$instanceId'
    | '/workflows/$workflowId'
    | '/workflows/new'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/instances'
    | '/templates'
    | '/instances/$instanceId'
    | '/workflows/$workflowId'
    | '/workflows/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  InstancesRoute: typeof InstancesRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  WorkflowsNewRoute: typeof WorkflowsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/new': {
      id: '/workflows/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof WorkflowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/$instanceId': {
      id: '/instances/$instanceId'
      path: '/$instanceId'
      fullPath: '/instances/$instanceId'
      preLoaderRoute: typeof InstancesInstanceIdRouteImport
      parentRoute: typeof InstancesRoute
    }
  }
}

interface InstancesRouteChildren {
  InstancesInstanceIdRoute: typeof InstancesInstanceIdRoute
}

const InstancesRouteChildren: InstancesRouteChildren = {
  InstancesInstanceIdRoute: InstancesInstanceIdRoute,
}

const InstancesRouteWithChildren = InstancesRoute._addFileChildren(
  InstancesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  InstancesRoute: InstancesRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  WorkflowsNewRoute: WorkflowsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
